### ISSUE TITLE
Open Source? Multi-room?

### ISSUE THREAD

**Issue by rcoe** [AetherThings/AetherCone#10]
Can you open source the code? Are there any plans to support multiroom?

**Comment by rtagraham** [comment]
+1 Multiroom connected Cones is surely not too much to ask? They used to connect but now we're forced to use individual cones.

**Comment by glenphelan** [comment]
I would love to see the code open-sourced, because a lot of users report Bluetooth connection issues.
It would be a great-value speaker if I could only connect to it without resetting it every time.
https://productforums.google.com/forum/#!msg/chromebook-central/v2qwMF3KBmQ/vI3Sa-cjBwAJ (That's me)
Also http://singletrackworld.com/forum/topic/psa-blutooth-wifi-speaker-thingy-aether-cone
And in the reviews here - http://www.appliancesdirect.co.uk/p/thecone-bc/aether-theconebc-desktop-pc-speaker#reviews

**Comment by rcoe** [comment]
@aronrosenberg How about it?

**Comment by aronrosenberg** [comment]
I wish I could release it, but its owned by the receiver and there are commercially licensed bits from Apple (AirPlay) and Spotify that could never be released.

**Comment by glenphelan** [comment]
I could live without AirPlay and Spotify - a standard Bluetooth speaker is all I want :-)
Multi-room would be a nice bonus, but I won't buy another Aether Cone until the one I have works...
I will happily donate to an open-source firmware project.

**Comment by aronrosenberg** [comment]
I wish I could release it, but its not owned by me or any of the other former Aether employees.
